version: "3.9"

services:
  db:
    image: postgres:15
    container_name: task-db
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: task-redis
    command: ["redis-server", "--appendonly", "yes"]

  api:
    build: ./api
    container_name: task-api
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_DB: "0"
      POSTGRES_HOST: db
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: ./worker
    container_name: task-worker
    environment:
      REDIS_HOST: redis
      REDIS_DB: "0"
      POSTGRES_HOST: db
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data: