[servers]
# Укажите IP-адрес или хост вашей виртуальной машины и порт для подключения
laravel-vm ansible_host=YOUR_SERVER_IP ansible_port=2222 # <-- Впишите сюда IP и порт (например, 127.0.0.1 и 2222)

[servers:vars]
# Укажите имя пользователя на удаленном сервере и путь к приватному SSH-ключу
ansible_user=YOUR_SSH_USER                              # <-- Впишите имя пользователя (например, test или debian)
ansible_ssh_private_key_file=~/.ssh/YOUR_PRIVATE_KEY     # <-- Впишите путь к вашему SSH-ключу (например, ~/.ssh/id_ed25519_debian)