---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Create keyring directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://download.docker.com/linux/debian/gpg \
      | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    executable: /bin/bash
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
    state: present
    update_cache: yes  # <--- Вот теперь этот параметр находится на своем месте внутри модуля apt_repository

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present

- name: Start Docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Install python docker sdk
  ansible.builtin.apt:
    name: python3-docker
    state: present