name: Full Monorepo CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - task-processor
          - task-processor-v1
        component:
          - api
          - worker

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ matrix.service }}-${{ matrix.component }}:latest \
            -f ./projects/${{ matrix.service }}/${{ matrix.component }}/Dockerfile \
            ./projects/${{ matrix.service }}/${{ matrix.component }}

      - name: Run container (smoke test)
        run: |
          docker run -d -p 3001:3001 --name app \
            ${{ matrix.service }}-${{ matrix.component }}:latest

          sleep 5
          curl --fail http://localhost:3001 || exit 1

          docker logs app
          docker stop app