name: Todo DevOps CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "examples/todo-devops/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "examples/todo-devops/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start services
        run: |
          cd examples/todo-devops
          docker compose up -d --build

      - name: Wait for service
        run: |
          cd examples/todo-devops

          for i in {1..20}; do
            curl -f http://localhost:5010/health && exit 0
            echo "waiting..."
            sleep 3
          done

          echo "Service failed"
          docker compose logs
          exit 1

      - name: Cleanup
        if: always()
        run: |
          cd examples/todo-devops
          docker compose down -v || true